version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: easygenerator-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: easygenerator
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - easygenerator-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # NestJS Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: easygenerator-backend:prod
    container_name: easygenerator-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/easygenerator?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - easygenerator-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  easygenerator-network:
    driver: bridge
